org_prefix: "*[RIVA] "
org_header_footer: |
  *[RIVA] A message from a RIVA Representative*

  %s

  _You are receiving this message because a RIVA Representative has initiated this communication. You are currently in communication with a RIVA Representative._
greeting_cooldown: 12
greeting_message: |
  *[RIVA] An automatic reply from RIVABot*

  Hi there, I am RIVABot! Thank you for contacting the Rivervale Primary School Alumni Association (RIVA) Community Outreach Team. We will reply you as soon as possible.

  In the mean time, are you following our socials?
  - Instagram (@riv.alumni)
  - Discord (go.riv-alumni.com/discord)
  - WhatsApp Group Chat (go.riv-alumni.com/whatsapp)

  Are you looking to participate in new events?
  1. Q3/4 Interest Gathering Form - https://go.riv-alumni.com/interest

  _You are receiving this message because you contacted us. You will be connected with a RIVA Representative._

